### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by marcellopato** [samuelhuarachi/laraveldocker#2]
Fiz exatamente como demonstrado no vídeo e ao rodar dá 404 not found.
Acho que é alguma configuração de path.

Vamos aos arquivos de conf:

- docker-compose.yaml
```
version: '3'
services:
  laravel-cnpj:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - cnpj-network
  mysql-app:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cnpj
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cnpj-network
networks:
  cnpj-network:
    driver: bridge
```
- .docker/nginx/default.conf
```
server {
    listen   80; ## listen for ipv4; this line is default and implied
    listen   [::]:80 default ipv6only=on; ## listen for ipv6

    root /usr/share/nginx/html;
    index index.php index.html index.htm;

    # Make site accessible from http://localhost/
    server_name _;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;

    # Security - Hide nginx version number in error pages and Server header
    server_tokens off;

    # Add stdout logging
    error_log /dev/stdout info;
    access_log /dev/stdout;

    # reduce the data that needs to be sent over network
    gzip on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml application/json text/javascript application/x-javascript application/x$
    gzip_disable "MSIE [1-6]\.";

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to index.html
        try_files $uri $uri/ /index.php?$query_string;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # pass the PHP scripts to FastCGI server listening on socket
    #
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
                expires           5d;
        }

    # deny access to . files, for security
    #
    location ~ /\. {
            log_not_found off;
            deny all;
    }

}
```

- Dockerfile
```
FROM wyveo/nginx-php-fpm:latest
WORKDIR /usr/share/nginx
RUN rm -rf /user/share/nginx/html
COPY . /user/share/nginx
RUN chmod -R 775 /user/share/nginx/storage/*
RUN ln -s public html
```

- .env
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:ljSzhlRMkkCf3HKipY+gYCXrWmEY8z9M3WmtznLghX4=
APP_DEBUG=true
APP_URL=http://localhost:8080

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=mysql-app
DB_PORT=3306
DB_DATABASE=cnpj
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

Quando rodo ```docker-compose up -d --build``` (build na primeira vez) ele monta tudo e abre o navegador em http://localhost:8080/ mas dá ```404 Not Found```

Tem alguma idéia do que pode ser, por favor?
